### ISSUE TITLE
ExiD Dataset anomaly

### ISSUE THREAD

**Issue by vinit-katariya** [RobertKrajewski/highD-dataset#15]
I am writing this email with respect to an anomaly that I observed in the ExiD dataset. Sorry to raise this issue in the HighD repo.

**Issue:**
The **_width and length_** columns in files xx_tracksMeta.csv and xx_tracks.csv are not matching for the same recordingId and trackId.

Can you please clarify which values are correct?

I also tried to connect to the regarding this through email, but the email address is not working.

**Comment by Naxter** [comment]
Hi! We already know about this issue (only regarding location 0). 
However, we are working on a new exid version with even better trajectories! With this update we will then also fix the width/length problems of location 0. 

As soon as it is ready, everyone (who accepted to receive updates) will receive an update e-mail with a link to the newer version.

As a "workaround", please use the width and length from the "xx_tracks.csv".

**Comment by vinit-katariya** [comment]
Thank you for the update.
